server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:

        - id: order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**, /orderStatuses/**
        - id: order_websocket
          uri: http://localhost:7081
          predicates:
            - Path=/rsocket/orders

        - id: delivery
          uri: http://localhost:8082
          predicates:
            - Path=/deliveries/**, 
        - id: delivery_websocket
          uri: http://localhost:7082
          predicates:
            - Path=/rsocket/deliveries

        - id: inventory
          uri: http://localhost:8083
          predicates:
            - Path=/inventories/**, /inventoryReadModels/**
        - id: inventory_websocket
          uri: http://localhost:7083
          predicates:
            - Path=/rsocket/inventories

        
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/orders/**, /orderStatuses/**
        - id: delivery
          uri: http://delivery:8080
          predicates:
            - Path=/deliveries/**, 
        - id: inventory
          uri: http://inventory:8080
          predicates:
            - Path=/inventories/**, /inventoryReadModels/**
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
